In [1]:
import os
os.getcwd()

'C:\\Users\\Gopi Raju\\Desktop\\remote internship\\dataset'

In [2]:
os.chdir("C:\\Users\\Gopi Raju\\Desktop\\remote internship\\dataset")
os.getcwd()

'C:\\Users\\Gopi Raju\\Desktop\\remote internship\\dataset'

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data=pd.read_csv("cereal.csv")
data

name mfr type  calories  protein  fat  sodium  \
0                    100% Bran   N    C        70      4.0  1.0     130   
1            100% Natural Bran   Q    C       120      3.0  5.0      15   
2                     All-Bran   K    C        70      4.0  1.0     260   
3    All-Bran with Extra Fiber   K    C        50      4.0  0.0     140   
4               Almond Delight   R    C       110      2.0  2.0     200   
..                         ...  ..  ...       ...      ...  ...     ...   
96                        Trix   G    C       110      1.0  1.0     140   
97                Waffle Crisp   K    C       110      2.0  1.0     165   
98                  Wheat Chex   R    C       100      3.0  1.0     230   
99                    Wheaties   G    C       100      3.0  1.0     200   
100        Wheaties Honey Gold   G    C       110      2.0  1.0     200   

     fiber  carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     10.0    5.0     6.0     280        25      3     1.0  0.33  68.402973  
1      2.0    8.0     8.0     135         0      3     1.0  1.00  33.983679  
2      9.0    7.0     5.0     320        25      3     1.0  0.33  59.425505  
3     14.0    8.0     0.0     330        25      3     1.0  0.50  93.704912  
4      1.0   14.0     8.0      -1        25      3     1.0  0.75  34.384843  
..     ...    ...     ...     ...       ...    ...     ...   ...        ...  
96     0.0   13.0    12.0      25        25      2     1.0  1.00  27.753301  
97     3.2   28.0     2.0      75        25      2     1.0  1.00  34.325100  
98     3.0   17.0     3.0     115        25      1     1.0  0.67  49.787445  
99     3.0   17.0     3.0     110        25      1     1.0  1.00  51.592193  
100    1.0   16.0     8.0      60        25      1     1.0  0.75  36.187559  

[101 rows x 16 columns]

In [4]:
data.isnull().any()

name        False
mfr         False
type        False
calories    False
protein     False
fat         False
sodium      False
fiber       False
carbo       False
sugars      False
potass      False
vitamins    False
shelf       False
weight      False
cups        False
rating      False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()
data['name']=labelencoder_x.fit_transform(data['name'])

In [6]:
data

name mfr type  calories  protein  fat  sodium  fiber  carbo  sugars  \
0       0   N    C        70      4.0  1.0     130   10.0    5.0     6.0   
1       1   Q    C       120      3.0  5.0      15    2.0    8.0     8.0   
2       2   K    C        70      4.0  1.0     260    9.0    7.0     5.0   
3       3   K    C        50      4.0  0.0     140   14.0    8.0     0.0   
4       4   R    C       110      2.0  2.0     200    1.0   14.0     8.0   
..    ...  ..  ...       ...      ...  ...     ...    ...    ...     ...   
96     96   G    C       110      1.0  1.0     140    0.0   13.0    12.0   
97     97   K    C       110      2.0  1.0     165    3.2   28.0     2.0   
98     98   R    C       100      3.0  1.0     230    3.0   17.0     3.0   
99     99   G    C       100      3.0  1.0     200    3.0   17.0     3.0   
100   100   G    C       110      2.0  1.0     200    1.0   16.0     8.0   

     potass  vitamins  shelf  weight  cups     rating  
0       280        25      3     1.0  0.33  68.402973  
1       135         0      3     1.0  1.00  33.983679  
2       320        25      3     1.0  0.33  59.425505  
3       330        25      3     1.0  0.50  93.704912  
4        -1        25      3     1.0  0.75  34.384843  
..      ...       ...    ...     ...   ...        ...  
96       25        25      2     1.0  1.00  27.753301  
97       75        25      2     1.0  1.00  34.325100  
98      115        25      1     1.0  0.67  49.787445  
99      110        25      1     1.0  1.00  51.592193  
100      60        25      1     1.0  0.75  36.187559  

[101 rows x 16 columns]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

NameError: name 'x' is not defined

In [8]:
x=data.iloc[:,0:3].values

y=data.iloc[:,3].values

In [9]:
x,y

(array([[0, 'N', 'C'],
        [1, 'Q', 'C'],
        [2, 'K', 'C'],
        [3, 'K', 'C'],
        [4, 'R', 'C'],
        [5, 'R', 'C'],
        [6, 'G', 'C'],
        [7, 'K', 'C'],
        [8, 'G', 'C'],
        [9, 'G', 'C'],
        [10, 'R', 'C'],
        [11, 'P', 'C'],
        [12, 'A', 'C'],
        [13, 'A', 'H'],
        [14, 'Q', 'C'],
        [15, 'G', 'C'],
        [16, 'A', 'C'],
        [17, 'G', 'C'],
        [18, 'G', 'C'],
        [19, 'G', 'C'],
        [20, 'R', 'C'],
        [21, 'K', 'C'],
        [22, 'K', 'C'],
        [23, 'G', 'C'],
        [24, 'K', 'C'],
        [25, 'N', 'H'],
        [26, 'K', 'C'],
        [27, 'G', 'C'],
        [28, 'A', 'C'],
        [29, 'R', 'C'],
        [30, 'Q', 'C'],
        [31, 'R', 'C'],
        [32, 'K', 'C'],
        [33, 'K', 'C'],
        [34, 'K', 'C'],
        [35, 'P', 'C'],
        [36, 'K', 'C'],
        [37, 'P', 'C'],
        [38, 'P', 'C'],
        [39, 'G', 'C'],
        [40, 'P', 'C'],
        [41, 'P', 'C'],
  

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [11]:
x_train

array([[62, 'G', 'C'],
       [3, 'K', 'C'],
       [71, 'N', 'C'],
       [45, 'G', 'C'],
       [48, 'K', 'C'],
       [6, 'G', 'C'],
       [100, 'G', 'C'],
       [82, 'N', 'C'],
       [76, 'R', 'C'],
       [60, 'K', 'C'],
       [80, 'R', 'H'],
       [91, 'G', 'C'],
       [68, 'Q', 'C'],
       [51, 'G', 'C'],
       [27, 'G', 'C'],
       [18, 'G', 'C'],
       [56, 'R', 'C'],
       [63, 'A', 'C'],
       [74, 'G', 'C'],
       [1, 'Q', 'C'],
       [61, 'K', 'C'],
       [42, 'P', 'C'],
       [41, 'P', 'C'],
       [4, 'R', 'C'],
       [15, 'G', 'C'],
       [17, 'G', 'C'],
       [40, 'P', 'C'],
       [38, 'P', 'C'],
       [5, 'R', 'C'],
       [92, 'G', 'C'],
       [59, 'K', 'C'],
       [0, 'N', 'C'],
       [34, 'K', 'C'],
       [28, 'A', 'C'],
       [50, 'Q', 'C'],
       [11, 'P', 'C'],
       [35, 'P', 'C'],
       [23, 'G', 'C'],
       [52, 'G', 'C'],
       [10, 'R', 'C'],
       [31, 'R', 'C'],
       [66, 'K', 'C'],
       [57, 'K', 'C'],
       [79, 'A',

In [12]:
x_test

array([[26, 'K', 'C'],
       [86, 'G', 'C'],
       [2, 'K', 'C'],
       [55, 'R', 'C'],
       [75, 'K', 'C'],
       [94, 'G', 'C'],
       [16, 'A', 'C'],
       [73, 'K', 'C'],
       [54, 'G', 'C'],
       [96, 'G', 'C'],
       [53, 'A', 'H'],
       [93, 'G', 'C'],
       [78, 'R', 'C'],
       [13, 'A', 'H'],
       [7, 'K', 'C'],
       [30, 'Q', 'C'],
       [22, 'K', 'C'],
       [24, 'K', 'C'],
       [33, 'K', 'C'],
       [8, 'G', 'C'],
       [43, 'N', 'C']], dtype=object)

In [13]:
y_train

array([130,  50, 160, 110, 140, 110, 110,  80, 110, 140,  90, 110,  50,
       110, 100, 110, 150,  47, 100, 120,  90, 120, 110, 110, 110, 120,
       100, 100, 165, 140, 120,  70, 100, 210, 100,  90, 120, 110, 250,
        90, 220, 100, 160, 250, 110, 110,  90, 120, 155, 110, 100, 110,
       100, 100, 100, 110, 140, 100, 110, 100, 110, 140, 110, 110, 100,
       100,  82,  90, 120, 100, 110, 120, 100,  90, 130, 110,  50, 120,
       110, 120], dtype=int64)

In [14]:
y_test

array([110, 155,  70, 150,  90, 110, 130, 120, 207, 110, 100, 100,  95,
       150, 110, 160, 110, 110, 110, 193, 150], dtype=int64)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc1=StandardScaler()
x_train=sc1.fit_transform(x_train)

ValueError: could not convert string to float: 'G'

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
x_train,x_test,y_train,y_test

(array([[62, 'G', 'C'],
        [3, 'K', 'C'],
        [71, 'N', 'C'],
        [45, 'G', 'C'],
        [48, 'K', 'C'],
        [6, 'G', 'C'],
        [100, 'G', 'C'],
        [82, 'N', 'C'],
        [76, 'R', 'C'],
        [60, 'K', 'C'],
        [80, 'R', 'H'],
        [91, 'G', 'C'],
        [68, 'Q', 'C'],
        [51, 'G', 'C'],
        [27, 'G', 'C'],
        [18, 'G', 'C'],
        [56, 'R', 'C'],
        [63, 'A', 'C'],
        [74, 'G', 'C'],
        [1, 'Q', 'C'],
        [61, 'K', 'C'],
        [42, 'P', 'C'],
        [41, 'P', 'C'],
        [4, 'R', 'C'],
        [15, 'G', 'C'],
        [17, 'G', 'C'],
        [40, 'P', 'C'],
        [38, 'P', 'C'],
        [5, 'R', 'C'],
        [92, 'G', 'C'],
        [59, 'K', 'C'],
        [0, 'N', 'C'],
        [34, 'K', 'C'],
        [28, 'A', 'C'],
        [50, 'Q', 'C'],
        [11, 'P', 'C'],
        [35, 'P', 'C'],
        [23, 'G', 'C'],
        [52, 'G', 'C'],
        [10, 'R', 'C'],
        [31, 'R', 'C'],
        [66, 'K', 'C'